name: eye-tracker
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - numpy=1.26.4
  - scikit-learn=1.5.2
  - pyside6=6.8.1
  - pip
  - pip:
    - opencv-python-headless==4.10.0.84
    - mediapipe==0.10.18
